name = "GregTech Odyssey"
version = "0.5.5-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35e78f5d45be94dce34a9be95455fe8ce631c077507992d88d8e092836f48c61"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
