name = "GregTech Odyssey"
version = "0.5.6-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b401f619f35d34ab121059158128cdf81abbcfb095523011b297959e0df202af"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
