name = "GregTech Odyssey"
version = "0.5.6-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b22f9871f06bc95375edfef190ead11adb0964555b2c515bbb768ab879f82534"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
